### ISSUE TITLE
PS3 Saves not Restoring automatically

### ISSUE THREAD

**Issue by AdmiringWorm** [MASGAU/MASGAU#10]
When trying to Restore a PS3 Save it would just throw an error, unless a similiar directory with the prefix and suffix already exists.

```
No restore paths detected for FinalFantasy13-2«PS3«EUR

   ved MASGAU.Restore.ARestoreProgramHandler`1.doWork(Object sender, DoWorkEventArgs e)
   ved System.ComponentModel.BackgroundWorker.WorkerThreadStart(Object argument)
```

**Comment by sanmadjack** [comment]
MASGAU is supposed to automatically create the paths for playstation saves, this is not correct behavipr.

**Comment by AdmiringWorm** [comment]
I believe I maybe have narrowed the problem down a little:
I changed this:

``` C#
if(test.GetDirectories(id.prefix + id.suffix + "*").Length>0) {
                    path.owner = null;
                    return_me.Add(path);
                }
```

to

``` C#
if(test.GetDirectories(id.prefix + id.suffix + "*").Length>0) {
                    path.owner = null;
                }
                return_me.Add(path);
```

Not a major change but it worked, now it detects if PS3\SAVEDATA is present, but not else.
I managed to track it even more down I believe:
On line 85 in MASGAU.Location.ALocationHandler you have this:

``` C#
if(global.hasFolderFor(get_me.rel_root)) 
```

this always seem to return null when restoring, no matter what eventhough the UserData user a few lines above can find it..

EDIT:
Seems I was completely wrong with this change, after this change it detected every PS3, PSP game in the xml's.

**Comment by AdmiringWorm** [comment]
I can't for the life of me figure out how to fixed it. Only thing I managed to do is finding out the same problem is for, PSP, PS1 and PS2 games
