### ISSUE TITLE
Submit Other button is centered

### ISSUE THREAD

**Issue by AdmiringWorm** [MASGAU/MASGAU#105]
The new button 'Submit Other' is being centered while
the other submit buttons are left-aligned.

![image](https://f.cloud.github.com/assets/1474648/2238868/2925ff70-9c06-11e3-951d-b0eb7262283e.png)

**Comment by sanmadjack** [comment]
Turns out it was real easy, I could actually just use a RibbonMenuItem. Change checking in now.
