### ISSUE TITLE
Identityreferences could not be translated

### ISSUE THREAD

**Issue by jarod186** [MASGAU/MASGAU#109]
After installing Masgau and then trying to start it up it gives an error message:

"Some or all Identityreferences could not be translated"
I get this erro both when starting single user and all user mode

See below screenshot

![image](https://cloud.githubusercontent.com/assets/13024088/8317988/8f63ac9a-1a01-11e5-90c7-a24cda003cef.png)

**Comment by AdmiringWorm** [comment]
This program seem to have ceased development, however this issue is the same as an issue which was resolved in the latest development build: which may be downloaded here: 

https://www.dropbox.com/s/01r3z7qdsugfo2o/MASGAU-1.0.8-Dev-Setup.exe?dl=0

Try it out and see if the issue is fixed for you.

**Comment by jarod186** [comment]
Hello, tried the 1.0.8 development build that was suggested, problem solved!! Thank you!! :)

**Comment by sanmadjack** [comment]
It's true, I haven't had time to work on this for awhile now. Thanks for stepping up, @AdmiringWorm !
