### ISSUE TITLE
Crash on startup (WHT THE HELL error)

### ISSUE THREAD

**Issue by dunestorm333** [MASGAU/MASGAU#113]
I get a crash as soon as I launch the software as admin. Judging from the debug info, it seems it thinks my username is Matthew, it isn't.

UPDATE: The "unstable" test version doesn't have this issue and launches normally...

>    at VDF.NestedElement..ctor(Queue`1 read) in C:\Users\Matthew\Desktop\MASGAU\Libs\VDF\NestedElement.cs:line 28
>    at VDF.NestedElement..ctor(Queue`1 read) in C:\Users\Matthew\Desktop\MASGAU\Libs\VDF\NestedElement.cs:line 42
>    at VDF.NestedElement..ctor(Queue`1 read) in C:\Users\Matthew\Desktop\MASGAU\Libs\VDF\NestedElement.cs:line 42
>    at VDF.NestedElementFile..ctor(String file_name) in C:\Users\Matthew\Desktop\MASGAU\Libs\VDF\NestedElementFile.cs:line 20
>    at MASGAU.Location.SteamLocationHandler.resetSteamPath() in C:\Users\Matthew\Desktop\MASGAU\MASGAU.Windows\Location\SteamLocationHandler.cs:line 63
>    at MASGAU.Location.LocationsHandler.setupSteamHandler() in C:\Users\Matthew\Desktop\MASGAU\MASGAU.Windows\Location\LocationsHandler.cs:line 10
>    at MASGAU.Location.ALocationsHandler.setup() in C:\Users\Matthew\Desktop\MASGAU\MASGAU.Common\Location\ALocationsHandler.cs:line 53
>    at MASGAU.AProgramHandler.doWork(Object sender, DoWorkEventArgs e) in C:\Users\Matthew\Desktop\MASGAU\MASGAU.Common\AProgramHandler.cs:line 52
>    at MASGAU.Main.MainProgramHandler.doWork(Object sender, DoWorkEventArgs e) in C:\Users\Matthew\Desktop\MASGAU\MASGAU.Common\AMainProgramHandler.cs:line 27
>    at System.ComponentModel.BackgroundWorker.OnDoWork(DoWorkEventArgs e)
>    at System.ComponentModel.BackgroundWorker.WorkerThreadStart(Object argument)

**Comment by sigmap** [comment]
Can confirm this error exists. There's no download for the test version so I cannot test that. Wish there was a solution to this or at least a build that wasn't so broken.

**Comment by AndrewSav** [comment]
Don't worry about the Matthew thing, it's just debug info, it should not prevent you from running. Whatever problem you have, this is not because of the username ;)
