### ISSUE TITLE
UI change request: Main backup/restore interface issues.

### ISSUE THREAD

**Issue by OranguTech** [MASGAU/MASGAU#23]
(I'll break these out into individual "issues" is desired)

The current interface is a weird hybrid between checkbox items and a standard listbox. It's quite confusing to select something by checking the box, then hitting "back this up" and have nothing or something else back up, or to say "Back up everything" and only see, say, 3 things go by...

Bare minimum rapid fix, change "Back this up" to "Back up selected", and "Back everything up" to "Backup checked items" or similar.

Suggest:

Select All/Select none buttons, one "backup" (or restore) button.

(At least for restore) clicking on header columns should sort by that column. Alternately - disable the ability to click on header columns, and implement a (different) way of filtering results. (Use case: User wantss to see only Mass Effect 2 saves (not settings) and need to sort by date to see which one he wants to restore.)

 Move "Redetect games/reload archives" button somewhere else, and/or change it to standard "refresh" icon. (Usually two arrows circling back on themselves.)

**Comment by sanmadjack** [comment]
What version are you running?

**Comment by sanmadjack** [comment]
I aks because check boxes were removed in 0.9, specifically because of the weirdness you're describing.

**Comment by sanmadjack** [comment]
Oh right, I added those other check boxes. Yeah, that is kind of confusing. Those are intended to control backups that are made using the scheduled backup and what games get watched by the monitor. That isn't really being communicated effectively at all.

**Comment by sanmadjack** [comment]
The interface is being overhauled, I'm going to try and address these concerns as best I can

**Comment by sanmadjack** [comment]
The interface re-write is complete. Please raise a new issue for any problems/suggestions for it.
