### ISSUE TITLE
Doesn't support other languages

### ISSUE THREAD

**Issue by sanmadjack** [MASGAU/MASGAU#4]

**Comment by AdmiringWorm** [comment]
Since my push didn't reference this issue automatically, I'll add it manually:
a4688de
- Added code to get Current User Region
- Changed code to use "en.xml" if no location and/or region xml found for current user
- Included nb-NO.xml to Translation project

**Comment by sanmadjack** [comment]
MASGAU now pulls all of its interface strings from an XML file. Now we just need languages.
