### ISSUE TITLE
Delete selected archives

### ISSUE THREAD

**Issue by AdmiringWorm** [MASGAU/MASGAU#56]
Add a button which allows the user to delete all selected archives, and/or a checkbox which allows the user to overwrite an existing archive with a new backed up one.

**Comment by sanmadjack** [comment]
I decided to add a delete archive button. The button has to be deliberate, while the checkbox option is the one that could be done accidentally.

**Comment by sanmadjack** [comment]
http://goo.gl/GQOuW Okay I added the delete button in this build. It also has the suppress duplicate messages thing added.

**Comment by AdmiringWorm** [comment]
Nice work, I tested it and it works great. However I noticed a problem with the custom list you implemented.
I'm guessing you are already aware of it, but I'll post it as a new Issue none the less.

**Comment by sanmadjack** [comment]
Excellent, marking this as resolved. I'm working on the listview bug, I was not aware of it beleive it or not :)
