### ISSUE TITLE
xml attribute submitted error

### ISSUE THREAD

**Issue by AdmiringWorm** [MASGAU/MASGAU#60]
When a game is submitted MASGAU adds a new attribute 'submitted="True"'.
However when MASGAU is launched after this has been added it throws an error.
It is a simple error:
MASGAU adds a value of 'True' with a big T (at least on my computer). if this is changed back to a lowercase 't' MASGAU doesn't complain anymore.

**Comment by sanmadjack** [comment]
this is strange, I've never had this happen...I'll look into it

**Comment by AdmiringWorm** [comment]
could be a different locale issue

**Comment by sanmadjack** [comment]
Could be. I added a bit so that it makes sure to convert it to lower case.

**Comment by AdmiringWorm** [comment]
still adds 'False' with a upper case though.

**Comment by sanmadjack** [comment]
Found that out yesterday, commiting the fix now
