### ISSUE TITLE
Suggestion: Manually analyze a path

### ISSUE THREAD

**Issue by AdmiringWorm** [MASGAU/MASGAU#62]
Is it possible to add the ability to manually analyze a path, since the games added to new.xml
doesn't get the ability to submit...

Something in the way it was before v 1.0

**Comment by sanmadjack** [comment]
Well the idea is that you add that path as a game, then just click submit and it takes care fo everything for you.

**Comment by AdmiringWorm** [comment]
I understand that, but I'm thinking of games that already exists but want to find for instance a registry key without manually searching through the registry myself and not adding the entry to custom.xml because of the issue #59 that I posted previously

**Comment by sanmadjack** [comment]
Issue #59 isn't an issue at all with this. If you add a custom entry through the window, the game version gets marked as:

```
<version os="Windows" release="Custom">
```

MASGAU still has a thing to prevent adding a game with the exact same name, but if you're just trying to add a game to scan it, then just give it a bogus name or call it something like Borderlands2Custom. Does this seem like an unreasonable process?

**Comment by AdmiringWorm** [comment]
Nah, it doesn't sound unreasonable. I just felt the need for either a standalone analyzer or something and liked how it was pre-v1.0.
But I understand, it's not really necessary and the way you think of is good enough.

**Comment by sanmadjack** [comment]
The whole idea is to try to make this easy enough for anyone to be able to add a game and submit it. Guys like you understand things well enough that you can use the "for dummies" system to be able to do whatever you want.

**Comment by sanmadjack** [comment]
The more I think about it, the more I think that being able to scan and submit detected games is a cool idea. Consider it incoming!

**Comment by sanmadjack** [comment]
Get ready for it!

**Comment by sanmadjack** [comment]
Give this a shot when you get the chance:

https://drive.google.com/file/d/0By2Mfv6zO9SkQkhVcHNDQm1EMGs/edit?usp=sharing

**Comment by AdmiringWorm** [comment]
That works great, actually better than I had in my mind when this issue was created.
I did notice something off though (only cosmetical).
The Submit Other button is somehow center aligned and looks just plain odd.
As can be seen below in the screenshot.
It's probably because it is a RibbonMenuButton instead of a RibbonMenuItem like the rest.

![image](https://f.cloud.github.com/assets/1474648/2238828/f0ed1532-9c03-11e3-9430-eeb07f548d81.png)

**Comment by sanmadjack** [comment]
Yeah, that's why it's off. There might be some way to get it to align, I just don't have the time immediately. Would you mind creating an issue for it so I don't forget?

**Comment by AdmiringWorm** [comment]
Okay, so I started to translate the new strings you created for these buttons,
and had a question. Do you plan to give the number of games selected as a parameter to the string 'SubmitSelectedGames'.
Just wondering since based of how many are selected (1, or more) the translation could be different (this is true for english as well of course).

**Comment by sanmadjack** [comment]
Yeah, it'll be the first parameter. I haven't set that part up yet for English.

**Comment by AdmiringWorm** [comment]
ok, I'll just translate it to a catch-all phrase until you do then.

**Comment by sanmadjack** [comment]
k, cool

**Comment by sanmadjack** [comment]
I decided to just go with "Selected Game(s)", I think the whole dynamic phrase thing is overkill for this particular item.
