### ISSUE TITLE
xml element <exclude/> not honored

### ISSUE THREAD

**Issue by AdmiringWorm** [MASGAU/MASGAU#63]
I noticed whenever I add the element <exclude path/filename="{file}"/> in the xml files
MASGAU still backup the excluded files.

**Comment by sanmadjack** [comment]
this would explain an error that was submitted for skyrim backing up a temp file

**Comment by sanmadjack** [comment]
The code for exclusions isn't there at all. How's that for professional.

**Comment by sanmadjack** [comment]
Care to test the updated code? Do I need to send you a build?

**Comment by AdmiringWorm** [comment]
Works great
