### ISSUE TITLE
Maximize Hides Windows Taskbar

### ISSUE THREAD

**Issue by AdmiringWorm** [MASGAU/MASGAU#68]
When maximizing MASGAU it covers the whole screen including the Windows Taskbar

**Comment by sanmadjack** [comment]
Definitely a problem

**Comment by sanmadjack** [comment]
Turns out to a WPF thing:
http://www.abhisheksur.com/2010/09/taskbar-with-window-maximized-and.html

**Comment by sanmadjack** [comment]
@AdmiringWorm , since you seem to be taking this on, I'm assigning the issue to you.

**Comment by sanmadjack** [comment]
Though it should be noted, if you're running Windows 8, this behavior could be considered normal!

**Comment by AdmiringWorm** [comment]
Ah, I didn't know that, I guess I'll need to do a check if the user runs windows 8 (or above) or not then.
I do find it odd that it is normal in windows 8 though, as long as it isn't a Metro/Store app.

**Comment by AdmiringWorm** [comment]
I opted out of doing the check for Windows 8, I was thinking about it but got to thinking
that if the user (like me) have the taskbar at the top they would have problems with closing, minimizing it and etc. As well as backup their game saves and restoring the saves.
I'm still doing some testing with the latest commit and have not encountered any problems, except if the user closes MASGAU when it is maximize and then launch it again and then tries to restore the program to it's inital state it goes into the size it was when it was maximized. I'll poke around a little to see if I can't fix that as well.

**Comment by sanmadjack** [comment]
I think it's better to have the taskbar showing, so ignore windows 8 behavior. Thanks for working on this.

**Comment by AdmiringWorm** [comment]
Okay, btw did you get the e-mail I sent you yesterday?
It's regarding another issue I came over while working on this.

**Comment by sanmadjack** [comment]
I don't think I did. Which address did you send it to? Is it something you can just make an issue for?

**Comment by AdmiringWorm** [comment]
I sent it too sanmadjack@masgau.org, I haven't made an issue for it since I have no idea what to file it under.

**Comment by sanmadjack** [comment]
Figures, the one address I didn't check. I'll respond momentarily.

**Comment by sanmadjack** [comment]
The fix works great! Awesome!
