### ISSUE TITLE
Proper backup restore in case of a fresh OS install

### ISSUE THREAD

**Issue by beppe9000** [MASGAU/MASGAU#98]
I've noticed that the game detection fails if there are no saved games on the system, thus preventing a proper restore in case of a fresh install of the OS.

So I propose to scan the backup folder and reverse lookup the save location.

If the location is known-able (eg. %Appdata% or %userprofile%/Documents  directory are, while the game installation directory is not (without more complez algorithms).) you should pop them in the list for restore only.

Hence you could also add a button to do this: "Restore All". (idk if there's one.)

Hope this gets implemented. It'll be very useful for those who don't want to make a save on each game they'd like to restore in case of a fresh install. 

Also you could add some option to hide (or auto-hide) the steam bar.

**Comment by OranguTech** [comment]
I've run into that as well, you may not realize you can double click the
archive file and it will open in MASGAU and offer to restore it.

**Comment by beppe9000** [comment]
I am running in portable mode, with no file type association. ;)
Maybe drag&drop ... However if this gets implemented would be a great addition to the feature set.

**Comment by AdmiringWorm** [comment]
Actually drag&drop is already supported, but it won't work if you are running MASGAU as an administrator.
You can also use the restore other... button and select all the archives you want to restore.
The only times I've noticed these won't work is if the save location is dependent on a file or folder inside the save game folders.

**Comment by sanmadjack** [comment]
To be clear, the drag and drop thing is not something I an resolve. Because running as an admin user technically means that you're running as a different user, Windows security will prevent the whole drag and drop thing.

**Comment by beppe9000** [comment]
Microsoft recomends splitting the user interface and things that need elevation in different exes. i think this is madness. i'm currently having one account: Administrator, so is not really a problem for me (i am using D&D. I play it too... lol)

**Comment by sanmadjack** [comment]
Believe it or not, MASGAU can do that. If you attempt a restore from single-user mode, and it detects a permission issue getting in the way, it will offer to start the a second all-users-mode copy of the EXE that will only perform the restore. So, you could drag-and-drop into the single user window, and should be able to go from there. It's not optimal, but security rarely leaves us with an optimal solution, especially where Microsoft is concerned.

**Comment by sanmadjack** [comment]
I got to thinking about this. What if I added an entry to the games list called "undetected games" that would show archives in the backup file for undetected games? Or add a check box that would cause undetected games that have archives to show up in the list. Thoughts?

**Comment by beppe9000** [comment]
I think that the main list should always show Detected Games + Undetected Games with Saves in Backup Folder all in the same list (Maybe with different color codes) like if those were detected.
This way it shoul use the pre-existing user interface comcept.

**Comment by sanmadjack** [comment]
My concern is that, all the way back to version 0.1, MASGAU's behavior has always been to only show detected games. I'm hesitant to change a default like that. I am liking the idea of adding a check box that allows non-detected games to be shown, and it can even save the setting so that, if you want it, it will always show those undetected games. But I don't think it's a good idea to make it the default.

**Comment by sanmadjack** [comment]
While working on this I noticed a bug with the restore code when the game is undetected, and the original location stored in the archive doesn't exist anymore. Going to create a new issue for it.

**Comment by sanmadjack** [comment]
Hey, @beppe9000 , I created a build that addresses some restore issues if nothing is detected. Would you mind giving it a shot?

https://drive.google.com/file/d/0By2Mfv6zO9SkMmlLMy14d0FxMWM/edit?usp=sharing

**Comment by sanmadjack** [comment]
I'm going to close this issue. If you encounter any problems with the new build, please create a new issue.

**Comment by beppe9000** [comment]
ok i posted a post that didn't make to here. It worked like a charm!

**Comment by sanmadjack** [comment]
Awesome! Glad it worked!
